### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by erxson** [ShyanInc/HDRezkaDownloader#1]
Фильм "Кухня. Последняя битва" получилось скачать. Попытался скачать "Наруто: Ураганные хроники", но не удалось
```
C:\Users\pro11\Desktop\HDRezkaDownloader-main>py main.py
Поиск: Наруто
1 - [Аниме] Название: Наруто | Год: 2002-2007 | Страна:  Япония | Жанр:  Боевые искусства
2 - [Аниме] Название: Наруто: Ураганные хроники | Год: 2007-2017 | Страна:  Япония | Жанр:  Приключения
3 - [Аниме] Название: Наруто 6 | Год: 2009 | Страна:  Япония | Жанр:  Приключения
4 - [Аниме] Название: Наруто 8: Кровавая тюрьма | Год: 2011 | Страна:  Япония | Жанр:  Приключения
5 - [Аниме] Название: Наруто 7: Потерянная башня | Год: 2010 | Страна:  Япония | Жанр:  Приключения
6 - [Аниме] Название: Наруто 4 | Год: 2007 | Страна:  Япония | Жанр:  Приключения
7 - [Аниме] Название: Наруто 5 | Год: 2008 | Страна:  Япония | Жанр:  Приключения
8 - [Аниме] Название: Наруто: Ниндзя в стране снега | Год: 2004 | Страна:  Япония | Жанр:  Приключения9 - [Аниме] Название: Наруто 3: Грандиозный переполох | Год: 2006 | Страна:  Япония | Жанр:  Приключения
10 - [Аниме] Название: Наруто 2: Великая битва | Год: 2005 | Страна:  Япония | Жанр:  Приключения
11 - [Аниме] Название: Наруто 9: Путь ниндзя | Год: 2012 | Страна:  Япония | Жанр:  Фэнтези
12 - [Аниме] Название: Наруто: Последний Фильм | Год: 2014 | Страна:  Япония | Жанр:  Приключения
13 - [Аниме] Название: Боруто: Наруто. Фильм | Год: 2015 | Страна:  Япония | Жанр:  Приключения
14 - [Аниме] Название: Боруто: Новое поколение Наруто | Год: 2017 - ... | Страна:  Япония | Жанр:  Приключения
Введите номер: 2
Traceback (most recent call last):
  File "C:\Users\pro11\Desktop\HDRezkaDownloader-main\main.py", line 15, in <module>
    downloader = Download(download_data)
  File "C:\Users\pro11\Desktop\HDRezkaDownloader-main\HDRezkaAPI\download.py", line 27, in __init__
    self.url = download_data['url']
TypeError: string indices must be integers
```

**Comment by erxson** [comment]
Я тут потыкал и походу оно никакое аниме не качает. Онли сериалы

**Comment by erxson** [comment]
Я в movie_info.py добавил на 43 строке, оно качает многосерийное аниме и мультики, но я не знаю как определить это фильм или сериал. Фильмы так не получится скачать(
```
elif 'cartoons' in self.url:
            return self.series_info()
        elif 'animation' in self.url:
            return self.series_info()
```
